description: 'Simple flow to ask for a user ID and password and device verification'
start: init
nodes:
  init:
    name: init
    use: init
    next:
      start: node_99ff948b
  failure:
    name: failureResult
    use: failureResult
    next: {}
  sucess:
    name: successResult
    use: successResult
    next: {}
  node_ac0b8060:
    name: askUserID
    use: askUserID
    next:
      submitted: node_b3429862
      not_found: node_b3429862
  node_06ed91b0:
    name: validatePassword
    use: validatePassword
    next:
      fail: failure
      locked: failure
      noPassword: failure
      success: node_0cee4c88
  node_b3429862:
    name: askPassword
    use: askPassword
    next:
      submitted: node_06ed91b0
  node_99ff948b:
    name: isKnownDevice
    use: isKnownDevice
    next:
      unknown_device: node_ac0b8060
      oidc_requires_login: node_ac0b8060
      known_device: sucess
  node_0cee4c88:
    name: addKnownDevice
    use: addKnownDevice
    next:
      success: sucess
      failure: failure
      device_already_exists: failure
editor:
  nodes:
    init:
      x: -602.6797102115594
      'y': 108.97673576881107
    failure:
      x: 1476.0878552859542
      'y': 268.5322832131025
    sucess:
      x: 1636.3564180228414
      'y': -170.38295790581407
    node_ac0b8060:
      x: 27.4188579494097
      'y': 98.36363625245298
    node_06ed91b0:
      x: 739.4832512955448
      'y': 96.9923086212356
    node_b3429862:
      x: 390.5286885413874
      'y': 106.24816216339482
    node_99ff948b:
      x: -385.16168154870394
      'y': 77.69237019924668
    node_0cee4c88:
      x: 1094.564257125076
      'y': 34.24067696910072